{% set python_min = "3.10" %}
{% set name = "remotior-sensus" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/remotior_sensus-{{ version }}.tar.gz
  sha256: 3e68730e6444978603086ff8fbedafcef4f5cc00cf03d74319bffc2a7db74507

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - gdal

test:
  imports:
    - remotior_sensus
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://fromgistors.blogspot.com/p/remotior-sensus.html
  dev_url: https://github.com/semiautomaticgit/remotior_sensus
  doc_url: https://remotior-sensus.readthedocs.io
  summary: Remotior Sensus is software to process remote sensing and GIS data
  license: GPL-3.0-or-later
  license_file:
    - src/remotior_sensus/COPYING

extra:
  recipe-maintainers:
    - semiautomaticgit
